basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is the API for the announcements service in GO with Gin Framework.
  title: Announcements service API
  version: 0.0.1
paths: {}
swagger: "2.0"
