apiVersion: apps/v1
kind: Deployment
metadata:
  name: announcements  # Match your API container name
  namespace: egs-yellowfy

spec:
  replicas: 1  # Adjust for desired number of API replicas
  selector:
    matchLabels:
      app: announcements  # Match the label in the pod template
  template:
    metadata:
      labels:
        app: announcements  # Label for pod selection
    spec:
      containers:
      - name: announcements
        image: registry.deti:5000/egs-yellowfy/announcements:v0
        ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "32Mi"
          cpu: "10m"
        limits:
          memory: "128Mi"
          cpu: "500mm"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: egs-yellowfy

spec:
  replicas: 1  # Adjust for desired number of MongoDB replicas
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"

# Create Service for auth_app
---
apiVersion: v1
kind: Service
metadata:
  name: announcements
  namespace: egs-yellowfy
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: announcements