version: '3.9'

services:
  api:
    image: announcements-api
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: {}
