version: '3'

networks:
  traefik_net:
    external: true

services:
  traefik:
    image: traefik:v3.0
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    restart: always
    ports:
      - "80:80"
      - "8080:8080" # The Web UI (enabled by --api)
    networks:
      - traefik_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
