version: '3'

services:
  web:
    build: ./auth_app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URI: "mysql+pymysql://root:root@db:3306/flask_app_db"
    depends_on:
      - db

  db:
    build: ./auth_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask_app_db
    ports:
      - "3306:3306"

